using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuControl : Control
{
    public MainMenuControl(IResourceCache resCache, IConfigurationManager configMan)
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.TopRight);
        LayoutContainer.SetMarginRight(VBox, -25);
        LayoutContainer.SetMarginTop(VBox, 30);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Begin);

        /* Everwood REMOVE
        var logoTexture = resCache.GetResource<TextureResource>("/Textures/_White/Logo/icon/icon-256x256.png"); // WD EDIT
        Logo.Texture = logoTexture;
        */

        var borderUpTexture = resCache.GetResource<TextureResource>("/Textures/_Everwood/Logo/border_up.png"); // Everwood
        BorderUp.Texture = borderUpTexture;

        var borderDownTexture = resCache.GetResource<TextureResource>("/Textures/_Everwood/Logo/border_down.png"); // Everwood
        BorderDown.Texture = borderDownTexture;

        var currentUserName = configMan.GetCVar(CVars.PlayerName);
        UsernameBox.Text = currentUserName;
    }
}
